version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/hitme
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv ENV
            . ENV/bin/activate
            pip install -r requirements.txt
      - run:
          name: run unit tests
          command: |
            . ENV/bin/activate
            cd hit_me_please && python manage.py test
